# billing — generated by the AutoDeployer Factory.
#
# Every image is pinned by *index* digest, not by tag. A tag moves: the same
# Dockerfile builds a different image next month, and a release rebuilt from its
# recorded commit would not reproduce — which is the whole point of recording
# one. The digests below are multi-architecture indexes, so this builds on the
# arm64 target and on an amd64 developer box; a per-architecture manifest digest
# would pin one and fail the other with `no matching manifest`.
#
# Builds run *on* the target (`docs/target-setup.md`), so this is a native build
# with no QEMU and no cross-compile.

# ── build ─────────────────────────────────────────────────────────────────────
FROM python:3.12-slim-bookworm@sha256:4766d8b510c428e595d74b9cc5bbb2fae8e26316fffb4adc89908d79aacd58a2 AS build

# uv rather than pip: `uv.lock` is the lockfile, and resolving it with a
# different tool at image-build time would make the deployed dependency set
# differ from the tested one in ways no test would catch.
COPY --from=ghcr.io/astral-sh/uv:0.11.10@sha256:bca7f6959666f3524e0c42129f9d8bbcfb0c180d847f5187846b98ff06125ead /uv /usr/local/bin/uv

ENV UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy \
    UV_PROJECT_ENVIRONMENT=/opt/venv

WORKDIR /src

# Dependencies before source, so this layer survives a source-only change.
#
# `--frozen` is load-bearing: it installs exactly what `uv.lock` records and
# fails if the lock does not satisfy `pyproject.toml`, rather than resolving
# afresh. A build that resolves is a build whose dependency set can differ from
# the one the tests ran against, and nothing downstream would notice.
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev --no-install-project

# ── runtime ───────────────────────────────────────────────────────────────────
FROM python:3.12-slim-bookworm@sha256:4766d8b510c428e595d74b9cc5bbb2fae8e26316fffb4adc89908d79aacd58a2 AS runtime

# Clause 5: logs go to stdout, unbuffered, so `docker service logs` shows an
# event when it happens rather than when a 4 KB buffer fills.
ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PATH="/opt/venv/bin:$PATH"

# Non-root. Every route in this app is unauthenticated — that is the IR's
# expressive limit and it is written down — so the blast radius of a bug in one
# of them is whatever this process can reach.
RUN groupadd --gid 10001 billing \
    && useradd --uid 10001 --gid 10001 --home-dir /app --no-create-home billing

COPY --from=build /opt/venv /opt/venv
WORKDIR /app
COPY --chown=billing:billing alembic.ini gap.toml ir.json ./
COPY --chown=billing:billing migrations ./migrations
COPY --chown=billing:billing seed ./seed
COPY --chown=billing:billing app ./app

USER billing

# Clause 2: a wildcard bind on $PORT. `EXPOSE` is documentation — the routing
# mesh reads the published port, not this — but it is what a reader checks first.
ENV PORT=8000
EXPOSE 8000

# Clause 1, as a Swarm healthcheck. `python -c` rather than curl or wget:
# neither is in this image, and adding one to run a health probe widens the
# attack surface of every container for a request the interpreter can already
# make. Without a healthcheck Swarm calls a task healthy the moment the process
# starts, and a broken release would never roll back.
HEALTHCHECK --interval=10s --timeout=3s --start-period=20s --retries=3 \
    CMD ["python", "-c", "import os,urllib.request,sys; \
sys.exit(0 if urllib.request.urlopen(f\"http://127.0.0.1:{os.environ.get('PORT','8000')}/healthz\", timeout=2).status == 200 else 1)"]

# `${PORT:-8000}` needs a shell to expand it, and `exec` is what stops that
# shell from staying PID 1. Without it the shell receives the SIGTERM and
# uvicorn never does: clause 6's "drain and exit 0 within 10s" silently becomes
# "killed at the end of the grace period", which looks identical in the logs and
# is not the same thing at all.
CMD ["/bin/sh", "-c", "exec uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000} --timeout-graceful-shutdown 10"]
