"""Alembic environment.

The database URL comes from `app.settings`, never from `alembic.ini`. A DSN in a
checked-in config file is a credential in the repository, and this application
already has a way to receive one — `DATABASE_URL_FILE`, pointing at a Docker
secret — that `alembic.ini` cannot express.
"""

from __future__ import annotations

from alembic import context

from app.models import Base
from app.settings import settings

#: What `--autogenerate` compares a live database against. The initial revision
#: was written from `ir.json` rather than autogenerated, but every revision you
#: add after it will use this.
target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """`alembic upgrade --sql`: emit SQL without connecting to anything."""
    context.configure(
        url=settings().database_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    from app.db import engine

    with engine().connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
